# Generated by Django 4.0.3 on 2022-04-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_qualification',
            name='staff',
        ),
        migrations.DeleteModel(
            name='staff_experience',
        ),
        migrations.DeleteModel(
            name='staff_profile',
        ),
        migrations.DeleteModel(
            name='staff_qualification',
        ),
    ]
