# Generated by Django 4.0.3 on 2022-04-01 11:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_staff_qualification_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_bank_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('Bank_name', models.CharField(max_length=100)),
                ('Branch_name', models.CharField(max_length=50)),
                ('Ifsc_code', models.CharField(max_length=50)),
                ('Account_no', models.CharField(max_length=30)),
                ('Pan_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_current_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('Door_no', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=50)),
                ('Village', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('Designation', models.CharField(max_length=100)),
                ('Name_of_institution', models.CharField(max_length=100)),
                ('Experience_from', models.DateField()),
                ('Experience_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_joining_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('Designation', models.CharField(max_length=50)),
                ('Date_of_joining', models.DateField()),
                ('Nature_of_appointment', models.CharField(max_length=50)),
                ('staff_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff_permanent_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('Door_no', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=50)),
                ('Village', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Scar', models.CharField(max_length=1000)),
                ('Mole', models.CharField(max_length=1000)),
                ('Blood_group', models.CharField(max_length=50)),
                ('Religion', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=100)),
                ('Caste', models.CharField(max_length=20, null=True)),
                ('Community', models.CharField(max_length=500, null=True)),
                ('Aadhaar_no', models.CharField(max_length=12)),
                ('Mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Alt_mob_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Mail_id', models.EmailField(max_length=254)),
                ('Martial_status', models.CharField(max_length=20)),
                ('Spouse_name', models.CharField(max_length=100, null=True)),
                ('Spouse_occupation', models.CharField(max_length=100, null=True)),
                ('Mother_name', models.CharField(max_length=100)),
                ('Mother_occupation', models.CharField(max_length=200)),
                ('Father_name', models.CharField(max_length=100)),
                ('Father_occupation', models.CharField(max_length=200)),
                ('Guardian_name', models.CharField(max_length=100, null=True)),
                ('Guardian_occupation', models.CharField(max_length=200, null=True)),
                ('Medical_History', models.CharField(max_length=1000, null=True)),
                ('Languages_known', models.CharField(max_length=200)),
                ('Mother_tongue', models.CharField(max_length=200)),
                ('Skills', models.CharField(max_length=1000)),
                ('Hobbies', models.CharField(max_length=1000)),
                ('Awards', models.CharField(max_length=1000, null=True)),
                ('Recognitions', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('Degree_name', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=100)),
                ('Year_of_passing', models.CharField(max_length=10)),
                ('Percentage', models.CharField(max_length=10)),
            ],
        ),
    ]
